# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift-client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-client
  pod 'SwiftProtobuf', '~> 1.15.0'

  target 'swift-clientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift-clientUITests' do
    # Pods for testing
  end

end
